### ISSUE TITLE
Problem when building with TexLive 2019

### ISSUE THREAD

**Issue by wangxa** [sikouhjw/zhangyu1000#1]
When compiling with the latest update of `TexLive 2019` (2020-02-25), I got many errors like this:
```
LaTeX Warning: Reference `LastPage' on page 66 undefined on input line 9.
```
This causes the empty TOC in the generated PDF.

The command used to build PDF is:
```bash
xelatex 1000.tex
```

**Comment by sikouhjw** [comment]
My English is not very good
You need to compile twice
```latex
xelatex 1000.tex
xelatex 1000.tex
```
or
```
latexmk -xelatex 1000.tex
```
You can refer to the `texdoc lshort` _sec2.8 Cross References_ or `texdoc latex2e` _sec7 Cross references_, LastPage is a feature from the _LastPage package_, You can open the instruction manual with `texdoc LastPage`

**Comment by wangxa** [comment]
I tried to change `\pageref{\LastPage}` to `\pageref*{\LastPage}` in `1000.tex`, but it will not fix the problem. I guess the problem is inside `ctex` package. By the way, for me debugging the `TeX`-like script is the most difficult task in programming.

**Comment by sikouhjw** [comment]
I can't repeat your problem. One solution is to
https://github.com/sikouhjw/zhangyu1000/blob/3d8d86e1f2e0b7580cb5c58740ad80bd3f3f9250/1000.tex#L63
Modified to
```latex
\fancyhead[LE,RO]{\bfseries --\thepage/67--}
```
The second solution is to provide a minimal working example, which I have constructed from the information available, and you try to compile to see if the problem has been replicated
```latex
\documentclass{ctexbook}
\usepackage{lastpage}
\usepackage{hyperref}
\begin{document}
  content
  \pageref{LastPage}
\end{document}
```

**Comment by wangxa** [comment]
Hi, I found the solution.

We need to run `xelatex 1000.tex` twice. 

Thank you.
